build: false

environment:
    PYTHON: "C:\\Python37"

    CONAN_REFERENCE: "libmodbus/3.1.6"
    CONAN_USERNAME: "joakimono"
    CONAN_LOGIN_USERNAME: "joakimono"
    CONAN_CHANNEL: "testing"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "https://api.bintray.com/conan/joakimono/conan"
    CONAN_STABLE_BRANCH_PATTERN: "master/*"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16


install:
  - set PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
